-- Ejecuta una vez en el SQL Editor de TU proyecto Supabase.
-- Mantiene las filas y columnas existentes. No publica el historial ni desactiva RLS.
begin;

create table if not exists public.jarvis_messages (
    id bigint generated by default as identity primary key,
    session_id uuid not null,
    role text not null check (role in ('user', 'assistant')),
    content text not null,
    created_at timestamptz not null default now()
);

alter table public.jarvis_messages add column if not exists session_id uuid;

create index if not exists jarvis_messages_session_created_idx
    on public.jarvis_messages (session_id, created_at desc);

alter table public.jarvis_messages enable row level security;

-- Esta versión usa la clave secreta SOLO en el servidor de Streamlit.
-- El backend filtra siempre por session_id. Los visitantes nunca reciben la clave.
-- Los permisos previos de otros roles y sus políticas no se modifican.
grant select, insert on table public.jarvis_messages to service_role;

-- Concede uso solo sobre la secuencia de la clave primaria, si existe.
do $$
declare seq text;
begin
    if exists (select 1 from information_schema.columns
               where table_schema = 'public' and table_name = 'jarvis_messages' and column_name = 'id') then
        seq := pg_get_serial_sequence('public.jarvis_messages', 'id');
        if seq is not null then
            execute format('grant usage on sequence %s to service_role', seq);
        end if;
    end if;
end $$;

commit;
